language: python
sudo: enabled
services:
    - mysql
python:
    - "3.7.3"
env:
    global:
     - TRAVIS=true
install:
    - pip install -r requirements.txt
script:
    - python main.py -S test
    - python main.py -G 1 1 localhost root
