language: python
sudo: enabled
services:
    - mysql
python:
    - "3.7.3"
env:
    global:
     - TRAVIS=true
before_install:
    - sudo mysql -e 'SHOW DATABASES;'
    - sudo mysql -e 'CREATE DATABASE pianyuan;'
    - sudo mysql -e 'select database();'
    - sudo mysql -e 'SHOW DATABASES;'
    - sudo mysql -e 'use sys;'
    - sudo mysql -e 'select database();'
# command to install dependencies
install:
    - pip install -r requirements.txt
script:
    - python main.py

