language: python
sudo: enabled
services:
    - mysql
python:
    - "3.7.3"
env:
    global:
     - TRAVIS=true
install:
    - pip install -r requirements.txt
script:
    - python setup.py install
    - pianyuan -S test
    - pianyuan -g 1 1 localhost root
