language: python
sudo: enabled
services:
    - mysql
python:
    - "3.5"
env:
    global:
     - TRAVIS=true
before_install:
    - mysql -e 'CREATE DATABASE IF NOT EXISTS pianyuan;'
    - mysql -e 'create table film( quality char(50),
        moive_name mediumblob, 
        url mediumblob,
        size char(50),
        flash_time char(50)
        );'
# command to install dependencies
install:
    - pip install -r requirements.txt
script:
    - python main.py

